stages:
  - test
  - build

variables:
  # Наш Registry доступен раннеру по имени контейнера в одной сети Docker
  REGISTRY_HOST: "gitlab-server-gitlab-1:5050"
  IMAGE_NAME: "$REGISTRY_HOST/root/taska1/predict_service"
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  UV_HTTP_TIMEOUT: "300"

# Стейдж тестирования (Работает стабильно)
run_tests:
  stage: test
  image: ghcr.io/astral-sh/uv:python3.11-bookworm-slim
  script:
    - uv sync --frozen
    - PYTHONPATH=predict_service uv run pytest predict_service/tests/
  tags:
    - docker

# Стейдж сборки и пуша
build_and_push:
  stage: build
  image: docker:24.0.7-cli
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
    # ВАЖНО: говорим докер-клиенту полностью отключить TLS/HTTPS для сборщика джобы
    DOCKER_TLS_CERTDIR: ""
  before_script:
    # Явно указываем http:// перед именем контейнера, чтобы уйти от HTTPS
    - echo "$CI_REGISTRY_PASSWORD" | docker login http://$REGISTRY_HOST -u $CI_REGISTRY_USER --password-stdin
  script:
    # Собираем образ из контекста predict_service
    - docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest -f predict_service/Dockerfile predict_service/
    # Пушим во внутреннее имя контейнера реестра
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:latest
  tags:
    - docker
  only:
    - main
    - dev
    - feature/server-deployment
