name: taska1

services:
  db:
    image: postgres:13-alpine
    container_name: pg_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-supersecret}
      POSTGRES_DB: ${POSTGRES_DB:-mlflow_db}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 3

  minio:
    image: quay.io/minio/aistor/minio
    container_name: minio-enterprise
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      # DevOps-практика: используем относительный путь от корня проекта
      - ./minio_data:/data
      - ./minio.license:/minio.license:ro
    command: server /data --console-address ':9001' --address ':9000'
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 15s
      timeout: 10s
      retries: 3

  s3_setup:
    image: minio/mc:RELEASE.2024-08-13T05-33-17Z
    container_name: s3_setup
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_USER_NAME: ${MINIO_USER_NAME}
      NINIO_USER_PASS: ${NINIO_USER_PASS}
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        mc alias set myminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}
        mc mb myminio/$${MINIO_BUCKET_NAME}/artifacts --ignore-existing
        mc admin user add myminio $${MINIO_USER_NAME} $${NINIO_USER_PASS}
        echo '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:*"],"Resource":["arn:aws:s3:::$${MINIO_BUCKET_NAME}","arn:aws:s3:::$${MINIO_BUCKET_NAME}/*"]}]}' > /tmp/mlflow_policy.json
        mc admin policy create myminio mlflow_restricted_policy /tmp/mlflow_policy.json
        mc admin policy attach myminio mlflow_restricted_policy --user=$${MINIO_USER_NAME}
        exit 0;
    networks:
      - backend_network

  mlflow_server:
    build: .
    image: mlflow_server
    container_name: mlflow_server
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    ports:
      # Меняем внешний порт с 5050 на 5060, чтобы не конфликтовать с GitLab Registry
      - "5080:5000"
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_USER_NAME}
      AWS_SECRET_ACCESS_KEY: ${NINIO_USER_PASS}
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      MLFLOW_S3_IGNORE_TLS: "True"
      # Передаем переменные внутрь контейнера для нашей CMD команды:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pg_data:

networks:
  backend_network:
    driver: bridge
