apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-predict-deployment
  namespace: predict-service-ns
  labels:
    app: fastapi-predict
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-predict
  template:
    metadata:
      labels:
        app: fastapi-predict
    spec:
      serviceAccountName: predict-service-sa
      imagePullSecrets:
        - name: gitlab-registry-credentials
      containers:
        - name: predict-container
          # Фиксируем белый IP (HTTPS для него полностью отключен патчем KinD!)
          image: 169.58.244.233:5050/root/taska1/predict_service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            # Трафик к MLflow и S3 пускаем по внутреннему шлюзу моста
            - name: MLFLOW_TRACKING_URI
              value: "http://172.18.0.1:5080"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://172.18.0.1:9000"
            - name: AWS_ACCESS_KEY_ID
              value: "Sanya_Cool_ML_specialist"
            - name: AWS_SECRET_ACCESS_KEY
              value: "IOidNIODiE&g67g&%g&6"
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
