apiVersion: v1
kind: Service
metadata:
  name: fastapi-predict-service
  namespace: predict-service-ns
spec:
  selector:
    app: fastapi-predict
  ports:
    - protocol: TCP
      port: 8000       # Внутренний порт сервиса (FastAPI)
      targetPort: 8000 # Порт внутри контейнера
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-predict-ingress
  namespace: predict-service-ns
  annotations:
    # Важно для KinD: этот контроллер триггерится именно по этой аннотации!
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: predict.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi-predict-service
                port:
                  number: 8000 # Перенаправляем трафик Ingress на порт сервиса 8000
