services:
  fastapi_predict:
    build:
      context: .
    container_name: fastapi_predict
    # УБРАЛИ network_mode: host, вернули изоляцию!
    ports:
      - "8000:8000"
    environment:
      # Теперь внутри общей сети мы можем обращаться к MLflow по имени контейнера!
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
    networks:
      - taska1_backend_network

networks:
  taska1_backend_network:
    external: true # Говорим докеру использовать уже существующую сеть проекта
